name: Update locale_z2m.json

on:
  schedule:
    - cron: '0 3 * * *'  # Läuft täglich um 03:00 Uhr UTC
  workflow_dispatch:  # Ermöglicht manuelle Ausführung über GitHub

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: JSON von API abrufen und speichern
        run: |
          curl -s https://api.crowdl.io/Z2MT/cdn/de.json -o temp.json
          jq '{translations: {de: .}}' temp.json > libs/locale_z2m.json
          rm temp.json

      - name: Änderungen überprüfen & committen
        run: |
          if git diff --quiet; then
            echo "Keine Änderungen – nichts zu committen."
          else
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add libs/locale_z2m.json
            git commit -m "Automatische Aktualisierung von locale_z2m.json"
            git push
          fi
